name: Build VyOS image for RPI 4 Model B

on:
  push:
    branches: [ "current" ]
    
jobs:
  build:

    runs-on: ubuntu-24.04-arm

    steps:
    - name: Checkout 
      uses: actions/checkout@v4
      
    - uses: addnab/docker-run-action@v3
      with:
        registry: docker.io
        image: tcnguyen/vyos-build:current-arm64
        shell: bash
        options: -v ${{ github.workspace }}:/vyos -v /dev:/dev --sysctl net.ipv6.conf.lo.disable_ipv6=0 --sysctl net.ipv4.conf.lo.forwarding=1
        run: |
          bin/bash -c 'cd /vyos; /bin/bash -x build-all.sh'
          
    - name: Find image file
      id: find_file
      run: |
        FILE=$(ls images/*.zip | head -n 1)
        BASENAME=$(basename "$FILE" .zip)
        echo "file_path=$FILE" >> $GITHUB_OUTPUT
        echo "release_name=$BASENAME" >> $GITHUB_OUTPUT

    - name: Show release info
      run: |
        echo "File path: ${{ steps.find_file.outputs.file_path }}"
        echo "Release name: ${{ steps.find_file.outputs.release_name }}"

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ steps.find_file.outputs.release_name }}
        release_name: ${{ steps.find_file.outputs.release_name }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ steps.find_file.outputs.file_path }}
        asset_name: ${{ steps.find_file.outputs.release_name }}.zip
        asset_content_type: application/zip
